import { readFileSync } from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

// public-submissions ticket 11, the half the config comment cannot enforce.
//
// The decision was to keep `/submit` in the sitemap. next-sitemap includes every
// route unless `exclude` names it, so the decision is only real while nobody adds
// an exclusion — and a generated file is regenerated by every build, so nothing
// about it is stable by default. These read the committed artifact, which is the
// one this repo ships.

const SITEMAP = readFileSync(
  path.join(process.cwd(), "public", "sitemap-0.xml"),
  "utf8"
)

const locs = Array.from(SITEMAP.matchAll(/<loc>([^<]+)<\/loc>/g), (m) => m[1])

describe("the committed sitemap", () => {
  it("lists /submit, which is ticket 11's decision", () => {
    // Found here by accident before the decision was made, and kept on purpose.
    // If this fails, either the route stopped building or something excluded it;
    // the `exclude` comment in next-sitemap.config.js is where the reasoning is.
    expect(locs).toContain("https://www.rnui.dev/submit")
  })

  it("names the www host on every URL and never the apex", () => {
    // The apex answers with a 307, so a sitemap full of apex URLs sends every
    // crawler through a redirect for no reason. This is the `siteUrl` line.
    expect(locs.length).toBeGreaterThan(0)
    for (const loc of locs) {
      expect(loc.startsWith("https://www.rnui.dev/")).toBe(true)
    }
  })

  it("still leaves the request-scoped routes out", () => {
    // `/` and `/products` await view and vote counts, which is what keeps them
    // from prerendering, and an unprerendered route is not in the manifest
    // next-sitemap reads. Pinned here because "why is the homepage missing from
    // the sitemap" is a question that gets answered by deleting the await.
    expect(locs).not.toContain("https://www.rnui.dev/")
    expect(locs).not.toContain("https://www.rnui.dev/products")
  })
})
